### ISSUE TITLE
Error displaying widget: model not found trying 02_single_stock_trade.ipnyb example

### ISSUE THREAD

**Issue by jeffmccune** [NVIDIA/fsi-samples#121]
Overview
===

Thanks for publishing this, it's very interesting and I appreciate the time and effort you're spending on it.  I'm trying to get started with [02_single_stock_trade.ipnyb](../tree/main/gQuant/plugins/rapids_plugin/notebooks/02_single_stock_trade.ipynb) with git tag v1.0.2 (abf9d337035c7d3ca11697e7fb4610156824b036) and when I load the notebook in Jupyter Lab, I get the following error in the `task_graph.draw()` cell.

Any suggestions to get the graph widget working?

```
Error displaying widget: model not found
```

```
[5]: task_graph.run(formated=True)
```

```
Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/site-packages/gquant/dataframe_flow/taskGraph.py", line 634, in run
    result = self._run(outputs=outputs, replace=replace,
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/site-packages/gquant/dataframe_flow/taskGraph.py", line 476, in _run
    self.build(replace, profile)
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/site-packages/gquant/dataframe_flow/taskGraph.py", line 400, in build
    node = task.get_node_obj(replace.get(task_id), profile,
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/site-packages/gquant/dataframe_flow/task.py", line 184, in get_node_obj
    modules = get_gquant_config_modules()
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/site-packages/gquant/dataframe_flow/task.py", line 45, in get_gquant_config_modules
    modules_list = {imod: config['ModuleFiles'][imod]
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/site-packages/gquant/dataframe_flow/task.py", line 45, in <dictcomp>
    modules_list = {imod: config['ModuleFiles'][imod]
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/configparser.py", line 1255, in __getitem__
    return self._parser.get(self._name, key)
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/jeff/miniconda3/envs/jupyter/lib/python3.8/configparser.py", line 434, in _interpolate_some
    raise InterpolationMissingOptionError(
configparser.InterpolationMissingOptionError: Bad value substitution: option 'my_node' in section 'ModuleFiles' contains an interpolation key 'modulepath' which is not a valid option name. Raw value: '%(MODULEPATH)s/my_node.py'
```

Environment:
===

Debian 10.8 amd64

```
❯ jupyter serverextension list
config dir: /home/jeff/miniconda3/envs/jupyter/etc/jupyter
    jupyter_server_proxy  enabled
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.7 OK
❯ jupyter labextension list
JupyterLab v3.0.7
/home/jeff/miniconda3/envs/jupyter/share/jupyter/labextensions
        bqplot v0.5.22 enabled OK
        gquantlab v1.0.0 enabled OK
        @pyviz/jupyterlab_pyviz v2.0.1 enabled OK (python, pyviz_comms)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
```

conda info
---

```
conda info

     active environment : jupyter
    active env location : /home/jeff/miniconda3/envs/jupyter
            shell level : 2
       user config file : /home/jeff/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/jeff/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jeff/miniconda3/pkgs
                          /home/jeff/.conda/pkgs
       envs directories : /home/jeff/miniconda3/envs
                          /home/jeff/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.19.0-14-amd64 debian/10 glibc/2.28
                UID:GID : 3001:3001
             netrc file : None
           offline mode : False
```

conda list
---

```
# packages in environment at /home/jeff/miniconda3/envs/jupyter:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20200923.2           h9c3ff4c_1    conda-forge
aiohttp                   3.7.3            py38h497a2fe_1    conda-forge
aiohttp-cors              0.7.0                    pypi_0    pypi
aioredis                  1.3.1                    pypi_0    pypi
anyio                     2.1.0            py38h578d9bd_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
arrow-cpp                 1.0.1           py38hc8b273f_18_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
aws-c-common              0.4.59               h36c2ea0_1    conda-forge
aws-c-event-stream        0.1.6                had2084c_6    conda-forge
aws-checksums             0.1.10               h4e93380_0    conda-forge
aws-sdk-cpp               1.8.70               h57dc084_1    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blessings                 1.7                      pypi_0    pypi
bokeh                     2.2.3            py38h578d9bd_0    conda-forge
boost                     1.72.0           py38h1e42940_1    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
bqplot                    0.12.22                  pypi_0    pypi
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.1                    pypi_0    pypi
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.5                   pypi_0    pypi
cfitsio                   3.470                hb418390_7    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4                    pypi_0    pypi
colorcet                  2.0.6              pyhd8ed1ab_0    conda-forge
colorful                  0.5.4                    pypi_0    pypi
configparser              5.0.1                    pypi_0    pypi
cryptography              3.4.4            py38h3e25421_0    conda-forge
cudatoolkit               11.0.221             h6bb024c_0    nvidia
cudf                      0.17.0          cuda_11.0_py38_gf56ef850e6_0    rapidsai
cudf_kafka                0.17.0          py38_gf56ef850e6_0    rapidsai
cudnn                     8.0.0                cuda11.0_0    nvidia
cugraph                   0.17.0          py38_gb58e49e8_0    rapidsai
cuml                      0.17.0          cuda11.0_py38_ga48e0ffbf_0    rapidsai
cupy                      8.0.0            py38hb7c6141_0    rapidsai
curl                      7.71.1               he644dc0_8    conda-forge
cusignal                  0.17.0          py38_ge853242_0    rapidsai
cuspatial                 0.17.0          py38_g897b304_0    rapidsai
custreamz                 0.17.0          py38_gf56ef850e6_0    rapidsai
cuxfilter                 0.17.0          py38_g340129d_0    rapidsai
cyrus-sasl                2.1.27               h3274739_1    conda-forge
cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
dask-cuda                 0.17.0                   pypi_0    pypi
dask-cudf                 0.17.0          py38_gf56ef850e6_0    rapidsai
datashader                0.11.1             pyh9f0ad1d_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2021.2.0         py38h578d9bd_0    conda-forge
dlpack                    0.3                  he1b5a44_1    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
faiss-proc                1.0.0                      cuda    conda-forge
fastavro                  1.3.2            py38h497a2fe_0    conda-forge
fastrlock                 0.5              py38h709712a_2    conda-forge
filelock                  3.0.12                   pypi_0    pypi
fiona                     1.8.13           py38h033e0f6_1    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
gdal                      3.0.4           py38h172510d_10    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h05acad5_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.7               h9c3ff4c_0    conda-forge
glib-tools                2.66.7               h9c3ff4c_0    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
google-api-core           1.26.0                   pypi_0    pypi
google-auth               1.26.1                   pypi_0    pypi
googleapis-common-protos  1.52.0                   pypi_0    pypi
gpustat                   0.6.0                    pypi_0    pypi
gquant                    1.0.2                    pypi_0    pypi
gquant-rapids-plugin      0.0.0                    pypi_0    pypi
gquantlab                 1.0.0                    pypi_0    pypi
grpc-cpp                  1.33.2               hf41bbd9_2    conda-forge
grpcio                    1.35.0                   pypi_0    pypi
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hiredis                   1.1.0                    pypi_0    pypi
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py38h578d9bd_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
ipykernel                 5.4.3                    pypi_0    pypi
ipython                   7.20.0           py38h81c977d_2    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonpath-ng               1.5.2                    pypi_0    pypi
jsonschema                3.2.0                      py_2    conda-forge
jupyter-server-proxy      1.6.0              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
jupyter_server            1.3.0            py38h578d9bd_0    conda-forge
jupyterlab                3.1.0a2                  pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.2.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kealib                    1.4.14               he4dc956_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcudf                   0.17.0          cuda11.0_gf56ef850e6_0    rapidsai
libcudf_kafka             0.17.0            gf56ef850e6_0    rapidsai
libcugraph                0.17.0          cuda11.0_gb58e49e8_0    rapidsai
libcuml                   0.17.0          cuda11.0_ga48e0ffbf_0    rapidsai
libcumlprims              0.17.0          cuda11.0_g8216947_0    nvidia
libcurl                   7.71.1               hcdd3856_8    conda-forge
libcuspatial              0.17.0          cuda11.0_g897b304_0    rapidsai
libdap4                   3.20.6               hd7c4107_1    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libfaiss                  1.6.3           h328c4c8_3_cuda    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgcrypt                 1.8.7                h36c2ea0_0    conda-forge
libgdal                   3.0.4               he6a97d6_10    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.7               h1f3bc88_0    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libgpg-error              1.41                 h9c3ff4c_0    conda-forge
libgsasl                  1.8.0                         2    conda-forge
libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             hd79254b_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libprotobuf               3.14.0               h780b84a_0    conda-forge
librdkafka                1.5.3                h54cafa9_0    conda-forge
librmm                    0.17.0          cuda11.0_gc4cc945_0    rapidsai
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                h9c3ff4c_3    conda-forge
libspatialite             4.3.0a            h2482549_1038    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libthrift                 0.13.0               h5aa387f_6    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               hd18ef5c_0    conda-forge
libwebp                   1.2.0                h3452ae3_0    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxgboost                1.3.0dev.rapidsai0.17      cuda11.0_0    rapidsai
libxml2                   2.9.10               hee79883_0    conda-forge
llvmlite                  0.35.0                   pypi_0    pypi
locket                    0.2.1                    pypi_0    pypi
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py38h497a2fe_3    conda-forge
mistune                   0.8.4           py38h497a2fe_1003    conda-forge
msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
multidict                 5.1.0            py38h497a2fe_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.2              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nccl                      2.7.8.1            h4962215_100    nvidia
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5                        py_0    conda-forge
nodejs                    12.4.0               he1b5a44_0    conda-forge
notebook                  6.2.0            py38h578d9bd_0    conda-forge
numba                     0.52.0           py38h51da96c_0    conda-forge
numexpr                   2.7.2                    pypi_0    pypi
numpy                     1.20.1           py38h18fd61f_0    conda-forge
nvidia-ml-py3             7.352.0                  pypi_0    pypi
nvtx                      0.2.3            py38h497a2fe_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencensus                0.7.12                   pypi_0    pypi
opencensus-context        0.1.2                    pypi_0    pypi
openjpeg                  2.3.1                hf7af979_3    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
orc                       1.6.6                he361544_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.2                    pypi_0    pypi
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.3                    pypi_0    pypi
panel                     0.9.7                      py_0    conda-forge
param                     1.10.1             pyhd3deb0d_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py38ha0e1e83_2    conda-forge
pip                       20.3.3           py38h06a4308_0  
pixman                    0.38.0            h516909a_1003    conda-forge
ply                       3.11                     pypi_0    pypi
poppler                   0.87.0               h4190859_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 hc2f5b80_3    conda-forge
proj                      7.0.0                h966b41f_5    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
protobuf                  3.14.0           py38h709712a_1    conda-forge
psutil                    5.8.0            py38h497a2fe_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-spy                    0.3.4                    pypi_0    pypi
py-xgboost                1.3.0dev.rapidsai0.17  cuda11.0py38_0    rapidsai
pyarrow                   1.0.1           py38hf66eee4_18_cuda    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
pyee                      7.0.4              pyh9f0ad1d_0    conda-forge
pygments                  2.8.0                    pypi_0    pypi
pynvml                    8.0.4                      py_1    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyppeteer                 0.2.2                      py_1    conda-forge
pyproj                    2.6.1.post1      py38h7521cb9_0    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.5                h7579374_1  
python-confluent-kafka    1.5.0            py38h1e0a361_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
rapids                    0.17.0          cuda11.0_py38_g180f433_165    rapidsai
rapids-xgboost            0.17.0          cuda11.0_py38_g180f433_165    rapidsai
ray                       1.2.0                    pypi_0    pypi
re2                       2020.11.01           h58526e2_0    conda-forge
readline                  8.1                  h27cfd23_0  
redis                     3.5.3                    pypi_0    pypi
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rmm                       0.17.0          cuda_11.0_py38_gc4cc945_0    rapidsai
rsa                       4.7.1                    pypi_0    pypi
rtree                     0.9.7            py38h02d302b_1    conda-forge
ruamel-yaml               0.16.12                  pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
scikit-learn              0.24.1           py38h658cfdd_0    conda-forge
scipy                     1.6.0            py38hb2138dd_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
shapely                   1.7.1            py38ha11d057_1    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sniffio                   1.2.0            py38h578d9bd_1    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
spdlog                    1.7.0                hc9558a2_2    conda-forge
sqlite                    3.33.0               h62c20be_0  
streamz                   0.6.2              pyh44b312d_0    conda-forge
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tbb                       2020.2               h4bd325d_3    conda-forge
tblib                     1.7.0                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
terminado                 0.9.2            py38h578d9bd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    1.7.7                h8efa9f0_3    conda-forge
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.56.2             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
traittypes                0.2.1                    pypi_0    pypi
treelite                  0.93             py38hadf7658_3    conda-forge
treelite-runtime          0.93                     pypi_0    pypi
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2021a                h7f98852_0    conda-forge
ucx                       1.8.1+g6b29558       cuda11.0_0    rapidsai
ucx-proc                  1.0.0                       gpu    rapidsai
ucx-py                    0.17.0          py38_g6b29558_0    rapidsai
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    pypi_0    pypi
websockets                8.1              py38h497a2fe_3    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
xarray                    0.16.2             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xgboost                   1.3.0dev.rapidsai0.17  cuda11.0py38_0    rapidsai
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py38h497a2fe_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zict                      2.0.0                    pypi_0    pypi
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.8                hdf46e1d_0    conda-forge
```

**Comment by avolkov1** [comment]
Yea, it's trying to load an example module but the path isn't set. Either comment it out in [gquantrc](https://github.com/NVIDIA/fsi-samples/blob/v1.0.2/gQuant/plugins/rapids_plugin/gquantrc):
<https://github.com/NVIDIA/fsi-samples/blob/v1.0.2/gQuant/plugins/rapids_plugin/gquantrc>
```
# my_node= %(MODULEPATH)s/my_node.py
```
Or export the environment variable `MODULEPATH` to the path where you have the modules listed in gquantrc. For the `my_node.py` it should be the path on your system to that file's directory i.e.
<https://github.com/NVIDIA/fsi-samples/tree/v1.0.2/gQuant/plugins/rapids_plugin/modules>

**Comment by jeffmccune** [comment]
@avolkov1 Thank you so much!  That fixed it.

```diff
diff --git a/gQuant/plugins/rapids_plugin/gquantrc b/gQuant/plugins/rapids_plugin/gquantrc
index e7b3346..95bfc46 100644
--- a/gQuant/plugins/rapids_plugin/gquantrc
+++ b/gQuant/plugins/rapids_plugin/gquantrc
@@ -1,2 +1,2 @@
 [ModuleFiles]
-my_node= %(MODULEPATH)s/my_node.py
+# my_node= %(MODULEPATH)s/my_node.py
```
